name: Build 

on:
  workflow_dispatch:
  push:
    branches: [ "master" ]

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4.2.2
      - name: Setup VCPKG
        uses: lukka/run-vcpkg@v11
        with:
          vcpkgDirectory: ${{ github.workspace }}\src\vcpkg
          runVcpkgInstall: false
          doNotCache: false
      - name: Install CMake
        uses: lukka/get-cmake@latest
      - name: Init with CMake
        run: cmake --preset=vcpkg ${{ github.workspace }}\src
      - name: Build with CMake
        run: cmake --build ${{ github.workspace }}\src\build
      - name: Upload Server Artifact
        uses: actions/upload-artifact@v4
        with:
          name: Server
          path: ${{ github.workspace }}\src\build\Debug\KomiServer.exe
      - name: Upload Client Artifact
        uses: actions/upload-artifact@v4
        with:
          name: Client
          path: ${{ github.workspace }}\src\build\Debug\KomiClient.exe
      - name: Upload dependencies
        uses: actions/upload-artifact@v4
        with:
          name: Dependencies
          path: ${{ github.workspace }}\src\build\Debug\*.dll

