name: Build 

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4.2.2
      - name: Setup with VCPKG
        uses: lukka/run-vcpkg@v11
        with:
          vcpkgDirectory: ${{ github.workspace }}\src\vcpkg
      - name: Run CMake
        uses: lukka/run-cmake@v10.8
        with:
          cmakeListsTxtPath: '${{ github.workspace }}\src\CMakeLists.txt'

